swagger: "2.0"
info:
  description: "Application permettant de contrôler depuis son téléphone une liste de lecture YouTube et Spotify à lire sur son ordinateur. Possibilité de rechercher des morceaux, d'en faire des playlists, puis de les stocker en base de données, tout en gérant un système d'inscription/de connexion pour différencier les utilisateurs."
  version: "0.0.1"
  title: "Smart Jukebox"
tags:
- name: "YouTube"
  description: "Operations about YouTube"
- name: "Spotify"
  description: "Operations about Spotify"
schemes:
- "https"
- "http"
paths:
  /login:
    post:
      tags:
      - "General"
      summary: Authentifie un utilisateur
      description: Crée un token permettant à l'utilisateur d'accéder aux contenus protégés
      parameters:
        - name: credentials
          in: body
          required: true
          description: Login et mot de passe de l'utilisateur
          schema:
            $ref: "#/definitions/Login-Credentials"
      responses:
        200:
          description: "Utilisateur connecté"
        400:
          description: "Invalid input"
    delete:
      tags:
      - "General"
      summary: Deconnecte un utilisateur
      description: Supprime le token de l'utilisateur
      parameters:
        - name: id
          in: query
          type: integer
          format: "int64"
          required: true
          description: Identifiant du token à supprimer
      responses:
        404:
          description: "Id not found"
        405:
          description: "Validation exception"
  /signup:
    post:
      tags:
      - "General"
      summary: Crée un utilisateur
      description: Crée un nouvel utilisateur avec les informations données
      parameters:
        - name: user
          in: body
          required: true
          description: Informations de l'utilisateur
          schema:
            $ref: "#/definitions/User"
      responses:
        200:
          description: "Utilisateur créé"
        405:
          description: "Invalid input"
    delete:
      tags:
      - "General"
      summary: Supprime un utilisateur
      description: Supprime les informations de l'utilisateur
      parameters:
        - name: id
          in: query
          type : integer
          format: "int64"
          required: true
          description: Identifiant de l'utilisateur à supprimer
      responses:
        404:
          description: "User not found"
        405:
          description: "Validation exception"
  /uniqueSongYouTube:
    get:
      tags:
      - "YouTube"
      summary: "Recupère la vidéo YouTube courante"
      description: ""
      operationId: "findCurrentVideo"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad request"
    delete:
      tags:
      - "YouTube"
      summary: "Vide la collection uniqueSongModelYouTube"
      description: ""
      operationId: "deleteVideo"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        404:
          description: "Video not found"
        405:
          description: "Validation exception"
    post:
      tags:
      - "YouTube"
      summary: "Ajoute une vidéo YouTube"
      description: ""
      operationId: "addVideo"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "id"
        in: "query"
        description: "ID of video that needs to be added to database"
        required: true
        type: "integer"
        format: "int64"
      responses:
        405:
          description: "Invalid input"
  /uniqueSongSpotify:
    get:
      tags:
      - "Spotify"
      summary: "Récupère la piste Spotify courante"
      description: ""
      operationId: "findCurrentAudio"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad request"
    delete:
      tags:
      - "Spotify"
      summary: "Vide la collection uniqueSongModelSpotify"
      description: ""
      operationId: "deleteAudio"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        404:
          description: "Audio not found"
        405:
          description: "Validation exception"
    post:
      tags:
      - "Spotify"
      summary: "Ajoute une piste Spotify"
      description: ""
      operationId: "addAudio"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "id"
        in: "query"
        description: "ID of audio that needs to be added to database"
        required: true
        type: "integer"
        format: "int64"
      responses:
        400:
          description: "Invalid input"
definitions:
  Signup-Credentials:
    type: object
    required: [login, password]
    properties:
      login: 
        type: string
      password:
        type: string

  Login-Credentials:
    type: object
    required: user
    properties:
      user:
        type: object
        properties:
          email:
            type: string
            format: email
          password:
            type: string
            format: password
  User:
    type: object
    required: user
    properties:
      user:
        type: object
        properties:
          username:
            type: string
          email:
            type: string
            format: email
          emailConf:
            type: string
            format: email
          password:
            type: string
            format: password
          passwordConf:
            type: string
            format: password
externalDocs:
  description: "GitHub de SmartJukebox"
  url: "https://github.com/gfloret/ProgWeb"